fprintf(...
	"For multi-scale detection we first create a single scale sliding window \n" + ...
    "Then created NMS function to remove overlapping boxes that have are overlapping \n" + ...
    "more than 15%. For multi-scale we rescaled the images for multiple times in a given range \n" + ...
    "(both scaled down and up). We played around with the numbers and managed to go from \n" + ...
    "41% average accuraccy to 58%. Hard negatives were also added to the training dataset \n" + ...
    "to improve detection.");