fprintf(...
	"The way I have approached this task was basically to first go ahead\n" + ... 
	"with the given values for cellSize = 6 and lambda = 0.1. I added a debuggin \n" + ...  
	"feature to flag the false negative and false positive images in order to investigate.\n" + ...
	"Upon observation I noticed that by reducing the cellSize to 4, facial\n" + ...
	"features are captured in a better way. Also split the training model into\n" + ...
	"multiple 'folds' and averaged out the value of w and b. Lambda was also\n" + ...
	"changed from 0.1 to 0.01.");