fprintf(...
	"The way we have approached this task was basically to first go ahead with the\n" + ... 
	"given values for cellSize = 6 and lambda = 0.1 and train the descriptor. Then we added a debuggin feature\n" + ...  
	"to flag the false negative and false positive images in order to investigate a bit more.\n" + ...
	"Upon observation we noticed that by reducing the cellSize to 4, facial features\n" + ...
	"are captured in a better way. Also split the training model into multiple\n" + ...
	"'folds' and averaged out the value of w and b. Lambda was also changed from\n" + ...
	"0.1 to 0.01.");